version: "3.8"

networks:
  laravel-bank-search:
    driver: bridge

volumes:
  database: ~

services:

  nginx:
    container_name: laravel-bank-search-nginx
    image: laravel-bank-search/nginx:${IMAGE_TAG:-latest}
    build:
      context: ./docker/nginx
      args:
        IMAGE_TAG: ${IMAGE_TAG:-latest}
    volumes:
      - .:/var/www/html
    ports:
      - ${APP_PORT:-80}:80
    networks:
      - laravel-bank-search
    depends_on:
      - php-fpm
      - mysql

  php-fpm:
    container_name: laravel-bank-search-php-fpm
    image: laravel-bank-search/php-fpm:${IMAGE_TAG:-latest}
    build:
      context: ./docker/php-fpm
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        APP_ENV: ${APP_ENV:-}
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - .:/var/www/html
    networks:
      - laravel-bank-search
    depends_on:
      - mysql

  mysql:
    container_name: laravel-bank-search-mysql
    image: mysql:8.0.32
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - database:/var/lib/mysql
    networks:
      - laravel-bank-search
